# Generated by Django 5.0.6 on 2024-05-17 02:12

import django.contrib.auth.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_ticketassignedto_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='NA', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tickets', through='apiv1.TicketAssignedTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
